-- ============================================================================
-- Golden Ridge Apartments - Seed Data
-- Sprint 3: Production Booking System
-- Run this AFTER 001_schema.sql
-- ============================================================================

-- Insert apartments
INSERT INTO apartments (number, name, slug, status, published, description_cs, description_en, capacity, size_sqm, bedrooms, bathrooms, base_price_eur, min_nights, amenities, photos)
VALUES
  (
    1,
    'Apartmán 1',
    'apartman-1',
    'FOR_RENT',
    true,
    'Útulný apartmán s výhledem na hory. Ideální pro páry hledající romantický únik do přírody. Apartmán nabízí moderní vybavení, plně zařízenou kuchyni a pohodlnou postel s kvalitní matrací. Z balkonu se můžete kochat panoramatickým výhledem na okolní kopce.',
    'Cozy apartment with mountain views. Ideal for couples seeking a romantic nature escape. The apartment offers modern amenities, a fully equipped kitchen, and a comfortable bed with a quality mattress. From the balcony, you can enjoy panoramic views of the surrounding hills.',
    2,
    45,
    1,
    1,
    120.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "balcony", "mountain-view"]'::jsonb,
    '["/images/apartments/apt-1-1.jpg", "/images/apartments/apt-1-2.jpg"]'::jsonb
  ),
  (
    2,
    'Apartmán 2',
    'apartman-2',
    'FOR_RENT',
    true,
    'Prostorný apartmán pro rodiny. Dvě ložnice a plně vybavená kuchyně umožňují pohodlný pobyt pro celou rodinu. Obývací pokoj s pohovkou nabízí prostor pro společné chvíle.',
    'Spacious family apartment. Two bedrooms and fully equipped kitchen allow comfortable stay for the whole family. Living room with sofa offers space for time together.',
    4,
    75,
    2,
    1,
    180.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "washer", "dishwasher"]'::jsonb,
    '["/images/apartments/apt-2-1.jpg", "/images/apartments/apt-2-2.jpg"]'::jsonb
  ),
  (
    3,
    'Apartmán 3',
    'apartman-3',
    'FOR_RENT',
    true,
    'Luxusní apartmán s terasou. Perfektní pro ty, kteří oceňují extra prostor a soukromí. Velká terasa je ideální pro ranní kávu s výhledem na hory.',
    'Luxury apartment with terrace. Perfect for those who appreciate extra space and privacy. Large terrace is ideal for morning coffee with mountain views.',
    6,
    95,
    2,
    2,
    250.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "washer", "terrace", "mountain-view"]'::jsonb,
    '["/images/apartments/apt-3-1.jpg", "/images/apartments/apt-3-2.jpg"]'::jsonb
  ),
  (
    5,
    'Apartmán 5',
    'apartman-5',
    'FOR_RENT',
    true,
    'Moderní studio s panoramatickým výhledem. Kompaktní, ale plně vybavený prostor pro páry nebo jednotlivce.',
    'Modern studio with panoramic views. Compact but fully equipped space for couples or individuals.',
    2,
    38,
    1,
    1,
    100.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "mountain-view"]'::jsonb,
    '["/images/apartments/apt-5-1.jpg"]'::jsonb
  ),
  (
    7,
    'Apartmán 7',
    'apartman-7',
    'FOR_RENT',
    true,
    'Rodinný apartmán s dětským koutkem. Ideální pro rodiny s malými dětmi. Bezpečné prostředí a hračky pro nejmenší.',
    'Family apartment with kids corner. Ideal for families with small children. Safe environment and toys for the little ones.',
    5,
    82,
    2,
    1,
    200.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "washer", "kids-friendly"]'::jsonb,
    '["/images/apartments/apt-7-1.jpg", "/images/apartments/apt-7-2.jpg"]'::jsonb
  ),
  (
    9,
    'Apartmán 9',
    'apartman-9',
    'FOR_RENT',
    true,
    'Exkluzivní penthouse s vlastní saunou. Nejvyšší standard v celém komplexu. Luxusní vybavení a soukromá sauna pro maximální relaxaci.',
    'Exclusive penthouse with private sauna. The highest standard in the entire complex. Luxury amenities and private sauna for maximum relaxation.',
    8,
    120,
    3,
    2,
    350.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "washer", "sauna", "terrace", "mountain-view"]'::jsonb,
    '["/images/apartments/apt-9-1.jpg", "/images/apartments/apt-9-2.jpg"]'::jsonb
  ),
  (
    12,
    'Apartmán 12',
    'apartman-12',
    'FOR_RENT',
    true,
    'Útulný apartmán v přízemí s přímým přístupem na zahradu. Ideální pro hosty se psy nebo ty, kteří preferují snadný přístup.',
    'Cozy ground floor apartment with direct garden access. Ideal for guests with dogs or those who prefer easy access.',
    4,
    65,
    2,
    1,
    160.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "garden", "pet-friendly"]'::jsonb,
    '["/images/apartments/apt-12-1.jpg"]'::jsonb
  ),
  (
    15,
    'Apartmán 15',
    'apartman-15',
    'FOR_RENT',
    true,
    'Apartmán s pracovním koutem. Ideální pro digital nomády a vzdálené pracovníky. Ergonomické pracovní místo a rychlé WiFi.',
    'Apartment with work corner. Ideal for digital nomads and remote workers. Ergonomic workspace and fast WiFi.',
    3,
    55,
    1,
    1,
    140.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "workspace", "fast-wifi"]'::jsonb,
    '["/images/apartments/apt-15-1.jpg"]'::jsonb
  ),
  (
    18,
    'Apartmán 18',
    'apartman-18',
    'FOR_RENT',
    true,
    'Romantický apartmán s krbem. Perfektní pro zimní víkendy. Atmosféra přímo vybízí k odpočinku u ohně.',
    'Romantic apartment with fireplace. Perfect for winter weekends. The atmosphere invites you to relax by the fire.',
    2,
    50,
    1,
    1,
    150.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "fireplace"]'::jsonb,
    '["/images/apartments/apt-18-1.jpg", "/images/apartments/apt-18-2.jpg"]'::jsonb
  ),
  (
    21,
    'Apartmán 21',
    'apartman-21',
    'FOR_RENT',
    true,
    'Velký rodinný apartmán se třemi ložnicemi. Prostor pro celou rodinu nebo skupinu přátel. Prostorná kuchyně a obývací pokoj.',
    'Large family apartment with three bedrooms. Space for the whole family or group of friends. Spacious kitchen and living room.',
    7,
    110,
    3,
    2,
    280.00,
    2,
    '["wifi", "parking", "kitchen", "tv", "washer", "dishwasher"]'::jsonb,
    '["/images/apartments/apt-21-1.jpg", "/images/apartments/apt-21-2.jpg"]'::jsonb
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  published = EXCLUDED.published,
  description_cs = EXCLUDED.description_cs,
  description_en = EXCLUDED.description_en,
  capacity = EXCLUDED.capacity,
  size_sqm = EXCLUDED.size_sqm,
  bedrooms = EXCLUDED.bedrooms,
  bathrooms = EXCLUDED.bathrooms,
  base_price_eur = EXCLUDED.base_price_eur,
  min_nights = EXCLUDED.min_nights,
  amenities = EXCLUDED.amenities,
  photos = EXCLUDED.photos,
  updated_at = NOW();

-- Verify seed data
SELECT number, name, slug, published, base_price_eur FROM apartments ORDER BY number;
